In [30]:
import random
import numpy as np

In [31]:
goal = {'A':(5,0),
        'B':(4,0),
        'C':(3,0),
        'D':(2,0),
        'E':(0,0),
        'F':(0,1),
        'G':(0,2),
        'I':(0,4),
        'H':(0,3),
        'J':(0,5),
        'K':(0,6),
        'L':(0,7),
        'M':(0,8),
        'N':(2,8),
        'O':(3,8),
        'P':(4,8),
        'Q':(5,8)
        }

In [32]:
class GridWorld():
    def __init__(self,start):
        self.x=start[0]
        self.y=start[1]
    
    
    def step(self, a, goal):
        # 0번 액션 :왼쪽 1번 : 위, 2번: 오른쪽, 3번 아래
        if a==0:
            self.move_left()
        elif a==1:
            self.move_up()
        elif a==2:
            self.move_right()
        elif a==3:
            self.move_down()
        reward = -1
        done = self.is_done(goal)
        return (self.x, self.y), reward, done

    def move_left(self):
        if self.y==0:
            pass
        elif self.y == 3 and self.x in [3,4,5,6]:
            pass
        elif self.y == 5 and self.x in [3,4,5,6]:
            pass
        elif self.y == 7 and self.x in [3,4,5,6]:
            pass
        elif self.x == 9:
            pass
        else:
            self.y -=1

    def move_right(self):
        if self.y == 1 and self.x in [3,4,5,6]:
            pass
        elif self.y == 3 and self.x in [3,4,5,6]:
            pass
        elif self.y == 5 and self.x in [3,4,5,6]:
            pass
        elif self.y == 8:
            pass
        elif self.x == 9:
            pass
        else:
            self.y +=1

    def move_up(self):
        if self.x==0:
            pass
        elif self.x == 7 and self.y == [2,4,6]:
            pass
        else:
            self.x -=1

    def move_down(self):
        if self.x==9:
            pass
        elif self.x == 2 and self.y == [2,4,6]:
            pass
        else:
            self.x +=1

    def is_done(self,goal):
        if self.x==goal[0] and self.y==goal[1]:
            return True
        else:
            return False

    def reset(self,start):
        self.x=start[0]
        self.y=start[1]
        return (self.x, self.y)
        
            

In [35]:
class QAgent():
    def __init__(self):
        self.q_table=np.zeros((10, 9, 4)) # q밸류 저장하는 변수, 모두 0으로 초기화
        self.eps = 0.9
        self.alpha = 0.01
    
    def select_action(self, s):
        # eps-greedy로 액션을 선택해준다.
        x,y = s
        coin = random.random()
        if coin < self.eps:
            action = random.randint(0,3)
        else:
            action_val = self.q_table[x,y,:]
            action = np.argmax(action_val)
        return action

    def update_table(self, transition):
        s, a, r, s_prime = transition
        x,y=s
        next_x, next_y = s_prime
        a_prime = self.select_action(s_prime)

        self.q_table[x,y,a] = self.q_table[x,y,a] + 0.1*(r + self.q_table[next_x, next_y, a_prime] - self.q_table[x,y,a])
    
    def anneal_eps(self):
        self.eps -= 0.03
        self.eps = max(self.eps, 0.1)

    def show_table(self):
        # 학습이 각 위치에서 어느 액션의 q 값이 가장 높았는지 보여주는 함수
        q_lst = self.q_table.tolist()
        data = np.zeros((10,9))
        for row_idx in range(len(q_lst)):
            row = q_lst[row_idx]
            for col_idx in range(len(row)):
                col = row[col_idx]
                action = np.argmax(col)
                data[row_idx, col_idx] = action
        print(data)

In [36]:
start_input = list(map(int,input('시작점(x,y)를 입력해주세요! : ').split()))
goal_input = input('목표지점을 입력해주세요! : ')
env = GridWorld(start_input)
agent = QAgent()
env.is_done(goal[goal_input])


for n_epi in range(1000):
    done = False

    s = env.reset(start_input)
    while not done:
        a = agent.select_action(s)
        s_prime, r, done = env.step(a,goal[goal_input])
        agent.update_table((s,a,r,s_prime))
        s = s_prime
    agent.anneal_eps()

agent.show_table()

시작점(x,y)를 입력해주세요! : 9 4
목표지점을 입력해주세요! : I
[[1. 2. 2. 2. 0. 0. 0. 0. 2.]
 [2. 2. 2. 1. 1. 0. 0. 1. 1.]
 [2. 1. 2. 1. 1. 1. 1. 2. 0.]
 [0. 0. 3. 1. 1. 1. 2. 1. 0.]
 [1. 1. 3. 1. 1. 1. 3. 0. 3.]
 [2. 0. 1. 1. 1. 1. 3. 3. 2.]
 [0. 2. 1. 1. 1. 1. 2. 3. 3.]
 [3. 3. 1. 0. 1. 0. 1. 1. 2.]
 [0. 0. 3. 0. 1. 2. 2. 3. 2.]
 [3. 3. 3. 2. 1. 2. 0. 2. 0.]]


In [86]:
res = [['1. 2. 2. 2. 0. 0. 0. 0. 2'],
 ['2. 2. 2. 1. 1. 0. 0. 1. 1'],
 ['2. 1. 2. 1. 1. 1. 1. 2. 0'],
 ['0. 0. 3. 1. 1. 1. 2. 1. 0'],
 ['1. 1. 3. 1. 1. 1. 3. 0. 3'],
 ['2. 0. 1. 1. 1. 1. 3. 3. 2'],
 ['0. 2. 1. 1. 1. 1. 2. 3. 3'],
 ['3. 3. 1. 0. 1. 0. 1. 1. 2'],
 ['0. 0. 3. 0. 1. 2. 2. 3. 2'],
 ['3. 3. 3. 2. 1. 2. 0. 2. 0']]

In [87]:
res2 = []

In [88]:
for i in res:
    res2.append(i[0].split('. '))

In [89]:
res2

[['1', '2', '2', '2', '0', '0', '0', '0', '2'],
 ['2', '2', '2', '1', '1', '0', '0', '1', '1'],
 ['2', '1', '2', '1', '1', '1', '1', '2', '0'],
 ['0', '0', '3', '1', '1', '1', '2', '1', '0'],
 ['1', '1', '3', '1', '1', '1', '3', '0', '3'],
 ['2', '0', '1', '1', '1', '1', '3', '3', '2'],
 ['0', '2', '1', '1', '1', '1', '2', '3', '3'],
 ['3', '3', '1', '0', '1', '0', '1', '1', '2'],
 ['0', '0', '3', '0', '1', '2', '2', '3', '2'],
 ['3', '3', '3', '2', '1', '2', '0', '2', '0']]

In [90]:
view = res2

In [91]:
conv = {'0':'←',
        '1':'↑',
        '2':'→',
        '3':'↓'}

In [92]:
for i in range(10):
    for j in range(9):
        view[i][j] = conv[res2[i][j]]

In [93]:
view

[['↑', '→', '→', '→', '←', '←', '←', '←', '→'],
 ['→', '→', '→', '↑', '↑', '←', '←', '↑', '↑'],
 ['→', '↑', '→', '↑', '↑', '↑', '↑', '→', '←'],
 ['←', '←', '↓', '↑', '↑', '↑', '→', '↑', '←'],
 ['↑', '↑', '↓', '↑', '↑', '↑', '↓', '←', '↓'],
 ['→', '←', '↑', '↑', '↑', '↑', '↓', '↓', '→'],
 ['←', '→', '↑', '↑', '↑', '↑', '→', '↓', '↓'],
 ['↓', '↓', '↑', '←', '↑', '←', '↑', '↑', '→'],
 ['←', '←', '↓', '←', '↑', '→', '→', '↓', '→'],
 ['↓', '↓', '↓', '→', '↑', '→', '←', '→', '←']]